services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # env_file:
    #   - .env                  # optional; keep if you actually ship a .env in your bundle
    environment:              # <-- pass EB env props into the container
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      S3_PREFIX: ${S3_PREFIX}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - sqlite_data:/data
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  sqlite_data:
